import { describe, expect, it } from 'vitest';
import type { CompiledBuildingPackage } from '@voicegis/map-compiler';
import referencePackageJson from '../../buildings/reference-medical-centre/compiled/building.package.json';
import {
  EXPLODED_FLOOR_GAP_METERS,
  computeBuildingBounds,
  getGraphSummary,
  getVisibleSpaces,
  mapCoordinateToWorld,
  visualFloorElevation,
} from './spatialTwinModel';

const referencePackage = referencePackageJson as unknown as CompiledBuildingPackage;

describe('spatial twin model', () => {
  it('centres the reference building from its compiled floor outlines', () => {
    expect(computeBuildingBounds(referencePackage)).toEqual({
      minX: 0,
      minY: 0,
      maxX: 30,
      maxY: 18,
      width: 30,
      depth: 18,
      center: [15, 9],
    });
  });

  it('maps source coordinates into a centred Three.js world', () => {
    const bounds = computeBuildingBounds(referencePackage);

    expect(mapCoordinateToWorld([15, 9], 3.6, bounds)).toEqual([0, 3.6, 0]);
    expect(mapCoordinateToWorld([0, 0], 0, bounds)).toEqual([-15, 0, -9]);
  });

  it('preserves surveyed elevation and adds a deterministic exploded-view gap', () => {
    const levelOne = referencePackage.floors.find((floor) => floor.id === 'l1');
    expect(levelOne).toBeDefined();
    expect(visualFloorElevation(levelOne!, false)).toBe(3.6);
    expect(visualFloorElevation(levelOne!, true)).toBe(3.6 + EXPLODED_FLOOR_GAP_METERS);
  });

  it('can isolate floors and exclude non-public spaces', () => {
    const groundSpaces = getVisibleSpaces(referencePackage, {
      floorId: 'g',
      includeRestricted: true,
    });
    const publicSpaces = getVisibleSpaces(referencePackage, {
      floorId: 'all',
      includeRestricted: false,
    });

    expect(groundSpaces).not.toHaveLength(0);
    expect(groundSpaces.every((space) => space.floorId === 'g')).toBe(true);
    expect(publicSpaces.every((space) => space.public && space.type !== 'restricted')).toBe(true);
    expect(publicSpaces.length).toBeLessThan(referencePackage.spaces.length);
  });

  it('summarises the graph generated by the compiler', () => {
    const summary = getGraphSummary(referencePackage);

    expect(summary).toMatchObject({ nodeCount: 55, edgeCount: 55, verticalEdgeCount: 2 });
    expect(summary.accessibleEdgeCount).toBeGreaterThan(0);
    expect(summary.restrictedEdgeCount).toBeGreaterThan(0);
  });
});
