import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const OFFLINE_CACHE_PREFIX = 'voicegis-visitor-';
const PUBLIC_FILE = /^(?:index\.html|favicon\.svg|manifest\.webmanifest|assets\/|venues\/)/;
const PUBLIC_BUNDLE_FORBIDDEN = [
  'BuildingSource workspace',
  'Operator tools',
  'Record a walk',
  '#/inspector',
  '#/studio',
  '#/recorder',
];
/*
 * Operator surfaces and the evidence pipeline. Sensor plumbing that both
 * surfaces need lives in src/sensors and is deliberately not listed here:
 * the visitor tracker asks for motion the same way, and a second copy of
 * the permission, visibility and revocation handling would drift from this
 * one in exactly the places that are hard to test.
 */
const OPERATOR_MODULE_SUFFIXES = [
  '/src/App.jsx',
  '/src/components/BuildingSourceWorkspace.tsx',
  '/src/components/SpatialTwinViewer.tsx',
  '/src/components/SurfaceNav.jsx',
  '/src/components/VenuePackageManager.jsx',
  '/src/components/WalkRecorder.tsx',
  '/src/components/SessionHarness.tsx',
  '/src/navigation/prepareDiagnosticSession.ts',
  '/src/capture/liveHandsetInput.ts',
];

async function filesBelow(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory())
      files.push(...(await filesBelow(path.join(directory, entry.name), relative)));
    else if (entry.isFile()) files.push(relative);
  }
  return files;
}

function digest(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * @param {string} outDir
 * @param {string} [base] where the build is served from, as Vite resolved it: `/` or `/name/`
 */
export async function collectOfflineEntries(outDir, base = '/') {
  const entries = [];
  for (const relative of (await filesBelow(outDir)).sort()) {
    const normalized = relative.replaceAll('\\', '/');
    if (normalized === 'sw.js' || normalized.endsWith('.map') || !PUBLIC_FILE.test(normalized)) {
      continue;
    }
    const bytes = await readFile(path.join(outDir, relative));
    entries.push({ url: `${base}${normalized}`, revision: digest(bytes) });
  }
  return entries;
}

export async function assertVisitorOnlyBundle(outDir) {
  // An earlier hook that threw leaves nothing written. Saying that plainly
  // beats a scandir stack trace standing in for the real build error.
  const assets = path.join(outDir, 'assets');
  if (!existsSync(assets)) {
    throw new Error(
      `Public build wrote no ${assets}; an earlier build error is the cause of this one.`,
    );
  }
  const javascriptFiles = (await filesBelow(path.join(outDir, 'assets'))).filter((file) =>
    file.endsWith('.js'),
  );
  const emitted = (
    await Promise.all(
      javascriptFiles.map((file) => readFile(path.join(outDir, 'assets', file), 'utf8')),
    )
  ).join('\n');
  const leaked = PUBLIC_BUNDLE_FORBIDDEN.filter((marker) => emitted.includes(marker));
  if (leaked.length > 0) {
    throw new Error(`Public build contains operator-only markers: ${leaked.join(', ')}`);
  }
}

export function operatorModulesIn(moduleIds) {
  return moduleIds
    .map((moduleId) => moduleId.replaceAll('\\', '/'))
    .filter((moduleId) => OPERATOR_MODULE_SUFFIXES.some((suffix) => moduleId.endsWith(suffix)));
}

/**
 * @param {{ url: string, revision: string }[]} entries
 * @param {string} [base]
 */
export function renderOfflineWorker(entries, base = '/') {
  const revision = digest(JSON.stringify(entries)).slice(0, 24);
  const cacheName = `${OFFLINE_CACHE_PREFIX}${revision}`;

  return `/* Generated by the VoiceGIS public build. Do not edit. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = ${JSON.stringify(OFFLINE_CACHE_PREFIX)};
const PRECACHE_ENTRIES = ${JSON.stringify(entries)};
const PRECACHE_BY_PATH = new Map(PRECACHE_ENTRIES.map((entry) => [entry.url, entry]));
const INDEX_PATH = ${JSON.stringify(`${base}index.html`)};

function bytesToHex(bytes) {
  return [...new Uint8Array(bytes)]
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}

async function responseDigest(response) {
  const bytes = await response.clone().arrayBuffer();
  return bytesToHex(await crypto.subtle.digest('SHA-256', bytes));
}

async function fetchVerified(entry) {
  const response = await fetch(entry.url, { cache: 'no-cache' });
  if (!response.ok || (await responseDigest(response)) !== entry.revision) {
    throw new Error(\`Offline asset did not match its build revision: \${entry.url}\`);
  }
  return response;
}

async function cacheVerifiedEntries(cache, entries) {
  const responses = await Promise.all(entries.map(fetchVerified));
  await Promise.all(entries.map((entry, index) => cache.put(entry.url, responses[index])));
}

async function verifiedResponse(entry) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(entry.url);
  if (cached && (await responseDigest(cached)) === entry.revision) return cached;

  // A cache miss under an old active worker can occur after storage eviction
  // while the server already hosts a newer release. Returning an ordinary
  // network response here would combine releases. Only the exact bytes this
  // worker precommitted may repair the miss; otherwise the request fails
  // closed and no newer bytes are admitted under the active release's identity.
  const response = await fetchVerified(entry);
  await cache.put(entry.url, response.clone());
  return response;
}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cacheVerifiedEntries(cache, PRECACHE_ENTRIES)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
        .map((name) => caches.delete(name)),
    );
    await self.clients.claim();
  })());
});

async function ensureOfflineCache() {
  const cache = await caches.open(CACHE_NAME);
  let missing = [];
  for (const entry of PRECACHE_ENTRIES) {
    const response = await cache.match(entry.url);
    if (!response || (await responseDigest(response)) !== entry.revision) missing.push(entry);
  }
  if (missing.length > 0) {
    try {
      await cacheVerifiedEntries(cache, missing);
    } catch {
      // The reply below stays false. An active worker is not evidence that its
      // storage survived eviction, and repair is impossible without a network.
    }
    const remaining = [];
    for (const entry of missing) {
      const response = await cache.match(entry.url);
      if (!response || (await responseDigest(response)) !== entry.revision) remaining.push(entry);
    }
    missing = remaining;
  }
  return missing.length === 0;
}

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'voicegis:verify-offline-cache') return;
  const reply = event.ports[0];
  event.waitUntil(
    ensureOfflineCache().then((complete) => {
      reply?.postMessage({ type: 'voicegis:offline-cache-status', complete });
    }),
  );
});

async function navigationResponse() {
  return verifiedResponse(PRECACHE_BY_PATH.get(INDEX_PATH));
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(navigationResponse());
    return;
  }

  const entry = PRECACHE_BY_PATH.get(url.pathname);
  if (entry) event.respondWith(verifiedResponse(entry));
});
`;
}

/** A served location the worker can own: an absolute path, so its scope and cache keys are exact. */
function workerBase(base) {
  if (typeof base !== 'string' || !base.startsWith('/') || !base.endsWith('/')) {
    throw new Error(
      `The public build needs an absolute base such as / or /name/ for its offline worker, not ${JSON.stringify(base)}.`,
    );
  }
  return base;
}

export function offlineServiceWorkerPlugin(enabled) {
  let outputDirectory;
  let base = '/';
  return {
    name: 'voicegis-offline-service-worker',
    apply: 'build',
    configResolved(config) {
      outputDirectory = config.build.outDir;
      if (enabled) base = workerBase(config.base);
    },
    generateBundle(_options, bundle) {
      if (!enabled) return;
      const moduleIds = Object.values(bundle).flatMap((output) =>
        output.type === 'chunk' ? Object.keys(output.modules) : [],
      );
      const leaked = operatorModulesIn(moduleIds);
      if (leaked.length > 0) {
        throw new Error(`Public build imported operator modules: ${leaked.join(', ')}`);
      }
    },
    async closeBundle() {
      if (!enabled) return;
      if (outputDirectory === undefined) throw new Error('Vite output directory was not resolved.');
      await assertVisitorOnlyBundle(outputDirectory);
      const entries = await collectOfflineEntries(outputDirectory, base);
      if (!entries.some(({ url }) => url === `${base}index.html`)) {
        throw new Error('Public build has no index.html to cache for offline navigation.');
      }
      if (!entries.some(({ url }) => url === `${base}venues/catalog.json`)) {
        throw new Error('Public build has no venue catalog to cache.');
      }
      await writeFile(
        path.join(outputDirectory, 'sw.js'),
        renderOfflineWorker(entries, base),
        'utf8',
      );
    },
  };
}
